port: 8080
security:
  secret: heehyyuhiouerheueuncdhhcuifopofyft
backends:
  backend:
    url: http://localhost:8081
  investment:
    url: http://localhost:8082
emailConfig:
  serverConfig:
    secret: my-secret