version: "3"
services:
  flyway:
    image: flyway/flyway
    container_name: auth_flyway
    command: -url=jdbc:postgresql://localhost:5432/backend -schemas=auth -user=backend -password=backend -connectRetries=60 migrate
    volumes:
      - ./flyway/:/flyway/sql/:Z
    network_mode: host