CREATE TABLE USERS(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME VARCHAR(256) UNIQUE NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE CUSTOMER_ROLES(
    ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID UUID,
    CONSTRAINT FK_CR_U_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);