CREATE TABLE USERS(
    ID UUID PRIMARY KEY,
    USERNAME VARCHAR(256) UNIQUE NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    IS_DELETED BOOLEAN NOT NULL
);

CREATE TABLE CUSTOMER_ROLES(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USER_ID UUID,
    CONSTRAINT FK_CR_U_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
)