CREATE TABLE auth.PASSWORD_RECOVERY
(
    ID              UUID PRIMARY KEY   DEFAULT gen_random_uuid(),
    CREATION_TIME   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRATION_DATE TIMESTAMP NOT NULL,
    EXECUTION_TIME  TIMESTAMP          DEFAULT NULL,
    USER_ID         UUID,
    UNUSED          BOOL               DEFAULT false,
    CONSTRAINT FK_PR_U_ID FOREIGN KEY (USER_ID) REFERENCES auth.USERS (ID) ON DELETE CASCADE
)