name: flyway
on:
  push:
    branches:
      - main

jobs:
  flyway:
    runs-on: ubuntu-latest
    needs: stopService
    steps:
      - name: Copy Flyway files
        uses: appleboy/scp-action@v0.1.4
        with:
          source: ./flyway/*
          target: /app/auth/
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
      - name: Run flyway
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: flyway -locations="filesystem:/app/auth/flyway" -schemas=auth migrate
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
      #      - name: Postgres Dump Backup
      #        uses: tj-actions/pg-dump@v2.3
      #        with:
      #          database_url: "postgres://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DEPLOY_HOST }}:5432/${{ secrets.DATABASE_NAME }}"
      #          path: "backup.sql"
      #          options: "-O"
      #      - uses: actions/upload-artifact@master
      #        with:
      #          name: backup
      #          path: ./backup.sql