name: pipeline
on:
  push:
    branches:
      - main

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/swagger
  build:
    needs:
      - swagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20.0"
          architecture: amd64
      - name: Build app
        run: env CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o main "./src/main.go"
      - uses: actions/upload-artifact@master
        with:
          name: main
          path: ./main
  stopService:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Stop service
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo service auth-service stop
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
  flyway:
    runs-on: ubuntu-latest
    needs: stopService
    steps:
      - uses: ./.github/workflows/flyway
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - stopService
      - flyway
    steps:
      - uses: ./.github/workflows/deploy