name: flyway
on:
  push:
    branches:
      - main

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20.0"
          architecture: amd64
      - name: Init swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Update Swagger
        run: chmod +x generateSwagger.sh && sh generateSwagger.sh
      - name: Commit message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          commit: --amend
          author_name: Mihael Macuka
          author_email: mihaelmacuka2@gmail.com
          message: ${{ env.COMMIT_MESSAGE }}
          add: 'docs/*'
          push: origin ${GITHUB_REF##*/} --force
          fetch: true